import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  compiler: {
    styledComponents: true,
  },
  experimental: {
    staleTimes: {
      dynamic: 30,
      static: 180,
    },
  },
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "cdn.sanity.io" },
      { protocol: "https", hostname: "ubuntuafrika-sl.com" },
    ],
  },
  async redirects() {
    const demoPaths = [
      "/sample-page",
      "/home-cyber-security",
      "/home-seo-company",
      "/contact-monochrome",
      "/contact-dark",
      "/contact-light",
      "/pricing-monochrome",
      "/pricing-dark",
      "/pricing-light",
      "/careers-monochrome",
      "/careers-dark",
      "/careers-light",
      "/about-us-monochrome",
      "/about-us-dark",
      "/about-us-light",
      "/home-biotech",
      "/portfolio-agency",
      "/careers-modern",
      "/pricing-modern",
      "/contact-modern",
      "/about-us-modern",
      "/home-crowdsourcing",
      "/home-app-landing",
      "/home-agency",
      "/home-dark-app",
      "/home-app-3",
      "/home-startup-2",
      "/home-help-center",
      "/home-product-promotion",
      "/home-saas",
      "/home-video",
      "/home-masonry-blog",
      "/home-cryptocurrency",
      "/portfolio",
      "/showcase",
      "/tour-2",
      "/tour",
      "/pricing",
      "/home-product-laptop",
      "/home-shop",
      "/home-parallax",
      "/home-startup",
      "/home-app-2",
      "/home-app",
      "/home-cloud",
      "/home-product-vr",
      "/shop-2",
      "/blog-standard-2",
      "/blog-masonry-sidebar",
      "/blog-standard-sidebar",
      "/blog-masonry-full",
      "/home-coming-soon",
      "/blog-masonry",
      "/my-account",
      "/checkout",
      "/cart",
      "/shop",
      "/support-help-faq",
      "/gallery",
      "/2015/03/05/effective-product-promo-videos",
      "/2015/03/03/this-is-a-quote",
      "/2015/03/02/gaining-exposure",
      "/2015/03/02/where-to-launch-your-startup",
      "/2015/03/02/top-development-frameworks-reviewed",
      "/2015/03/02/stunning-product-photography",
      "/2015/03/02/attracting-great-talent",
      "/2015/03/01/sourcing-audio-for-your-promo-video",
      "/2015/02/27/top-10-tips-for-working-from-home",
      "/2015/02/05/this-is-a-link-post",
      "/2015/02/04/usability-testing",
      "/2015/01/27/workspace-ideas",
      "/2015/01/06/exploring-intuitive-ux-design",
      "/2015/01/02/how-to-maximize-productivity",
      "/2015/01/01/making-the-most-of-your-commute",
      "/2023/02/23/hello-world",
    ];

    return demoPaths.map((source) => ({
      source,
      destination: "/",
      permanent: true,
    }));
  },
};

export default nextConfig;
