import type { AlumniRecord } from "@/types/content";

export const alumni: AlumniRecord[] = [
  {
    name: "Augustine Matturi",
    cohort: "2018 - 2019",
    photo: "/images/matturi.png",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Mattru Jong",
    familyPlace: "Freetown",
    job: "Junior Software Developer Ubuntu Tech Project in IT area.",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp: "Support Social Cooperation Projects for Ubuntu Africa in Sierra Leone.",
    contact: "a.saffa@ubuntuafrika.com / Telno +232 76359547",
    family: "Not married without children, Brothers, Sisters, Mother and Father.",
    age: "26",
    grade: "Superado Excelencia.",
  },
  {
    name: "Gabriel Tholley",
    cohort: "2018 - 2019",
    photo: "/images/Gabriel.png",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Makali",
    familyPlace: "Makeni",
    job: "Research Teaching Assistant",
    organization: "UNIMAK (Catholic University of Makeni) (Makeni, Sierra Leone).",
    socialHelp: "Support Ernest Bai Koroma University in Sierra Leone.",
    contact: "tgkapr@gmail.com/ Telno +232 78487813",
    family: "Married with no children, Brothers, Sisters, Mother and Father",
    age: "31",
    grade: "Superado Excelencia.",
    internalNotes:
      "Nota. Inicialmente fue contrado por la Fundación Ubuntu Africa para la segunda fase del Proyecto pero a los cinco meses se le invitó a dejarlo por el alto absentismo laboral.",
  },
  {
    name: "Lukeman Kamara",
    cohort: "2018 - 2019",
    photo: "/images/lookman-1.png",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Kamalo",
    familyPlace: "Kamalo",
    job: "Junior Software Developer Ubuntu Tech Project in IT area.",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp: "Support Social Cooperation Projects for Ubuntu Africa in Sierra Leone.",
    contact: "l.kamara@ubuntuafrika.com / Telno +232 77582802",
    family: "Not married with a child, Brothers, Sisters, Mother and Father.",
    age: "32",
    grade: "Superado Excelencia.",
  },
  {
    name: "Moses A. Kargbo",
    cohort: "2018 - 2019",
    photo: "/images/moses.png",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Maforaka",
    familyPlace: "Makeni",
    job: "Research Teaching Assistant",
    organization: "UNIMAK (Catholic University of Makeni)",
    socialHelp: "Secondary Schools.",
    contact: "moseskargbo651@gmail.com/ Telno +23278042108",
    family: "Married with two children, Brothers, Sisters, Mother.",
    age: "28: 31",
    grade: "Superado satisfactoriamente.",
  },
  {
    name: "Christopher Awolowo",
    cohort: "2018 - 2019",
    photo: "/images/awolo.png",
    residence: "Freetown (Sierra Leone)",
    birthPlace: "Freetown",
    familyPlace: "Freetown",
    job: "IT Consultant",
    organization: "BDO",
    socialHelp: "Support social project in Believe Vision Network.",
    contact: "christopherreffell24@gmail.com/ Telno +23279928444",
    family: "Not married with one child, Brothers, sisters, mother and father",
    age: "28",
    grade: "Superado satisfactoriamente.",
  },
  {
    name: "Alaji Kanu",
    cohort: "2018 - 2019",
    photo: "/images/alhaji.png",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Makeni",
    familyPlace: "Makeni",
    job: "Junior Software Developer Ubuntu Tech Project in IT area.",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp: "Support Social Cooperation Projects for Ubuntu Africa in Sierra Leona.",
    contact: "a.kanu@ubuntuafrika.com / Telno +232 77150549",
    family: "Married with two children, Brothers, Sisters.",
    age: "31",
    grade: "Superado satisfactoriamente",
    internalNotes:
      "Nota. Empezó a trabajar en Ubuntu Tech Project desde Marzo sustituyendo a Gabriel Tholley. Anteriormente en el perido Octubre 2019-Febrero 2020 estuvo dando clases en una escuela secundaria.",
  },
  {
    name: "Louis Momodu Conteh",
    cohort: "2018 - 2019",
    photo: "/images/louis.png",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Kabala",
    familyPlace: "Kabala",
    job: "Data Officer",
    organization: "UNIMAK (Catholic University of Makeni)",
    socialHelp: "Support IT project in Directorate of ICT.",
    contact: "louismo80@gmail.com/ Telno +23278646321",
    family: "Not married with one child, Brothers, sisters, mother and father.",
    age: "30",
    grade: "Superado satisfactoriamente.",
  },
  {
    name: "Abdulai Brato",
    cohort: "2018 - 2019",
    photo: "/images/brato.png",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Makeni",
    familyPlace: "Makeni",
    job: "Masters student in Software Engineering area in China.",
    organization: "Nakia University of Technology( Nakia, China)",
    socialHelp: "Students.",
    contact: "abdulaibratokamara@gmail.com/ Telno +8613702040205",
    family: "Married with two children, Brothers, Sisters, Mother and Father.",
    age: "30",
    grade: "Superado satisfactoriamente.",
    internalNotes:
      "Nota. Ha manifestado su interés por trabajar para la Fundación Ubuntu África cuando finalice el postgrado que realiza en China.",
  },
  {
    name: "Alusine Kamara",
    cohort: "2018 - 2019",
    photo: "/images/alusine.png",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Makeni",
    familyPlace: "Makeni",
    job: "Examination officer",
    organization: "Africa Accent Institute of Technology",
    socialHelp: "Support IT project in Schools.",
    contact: "kentysonk@gmail.com/ Telno +23277899545",
    family: "Not married with one child, Brothers, sisters, mother and father.",
    age: "35",
    grade: "Superado satisfactoriamente.",
  },
  {
    name: "Gibrilla Kanu",
    cohort: "2021 - 2022",
    photo: "/images/MG_2295.jpg",
    residence: "30 Manekeh, Kabala Highway Makeni Northern District",
    birthPlace: "Fretown Sierra Leone",
    familyPlace: "Freetown, Sierra Leone",
    job: "Junior Software Developer Ubuntu Tech Project in IT area.",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp: "Support Social Cooperation Projects for Ubuntu Africa in Sierra Leone.",
    contact: "g.kanu@ubuntuafrika.com / Telno +23278278531",
    family: "Not married without children, Brothers, Sisters, Mother and Father.",
    age: "28",
    grade: "Superado Excelencia.",
  },
  {
    name: "Alhaji Manasaray",
    cohort: "2021 - 2022",
    photo: "/images/MG_2267.jpg",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Makeni",
    familyPlace: "Makeni",
    job: "Junior Software Developer Ubuntu Tech Project in IT area",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp: "Support Social Cooperation Projects for Ubuntu Africa in Sierra Leone.",
    contact: "a.mansaray@ubuntuafrika.com / Telno +23277223999",
    family: "Not married without children, Brothers, Sisters, Mother and Father. (Mariama Mansaray, Idriss Allieu Mansaray)",
    age: "32",
    grade: "Superado Excelencia.",
  },
  {
    name: "Abdul Andrew Ojuku Kamara",
    cohort: "2021 - 2022",
    photo: "/images/MG_2272.jpg",
    residence: "15 Sakaty street Ropolon Makeni (Sierra Leone)",
    birthPlace: "Makeni",
    familyPlace: "15 Sakaty street Makeni",
    job: "Junior Software Developer Ubuntu Tech Project in IT area.",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp: "Support Social Cooperation Projects for Ubuntu Africa in Sierra Leone.",
    contact: "abdul.kamara@ubuntuafrika.com / Telno +232 88889449",
    family:
      "In a relationship, Brothers- 4, Sisters- 3, Mother-jane koroma and Father -abdul ojuku kamara.",
    age: "34",
    grade: "Superado Excelencia.",
  },
  {
    name: "John A Kamara",
    cohort: "2021 - 2022",
    photo: "/images/MG_2280.jpg",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Kamakwir",
    familyPlace: "Makeni and Kamakwie",
    job: "Research Teaching Assistant",
    organization: "UNIMAK (Catholic University of Makeni)",
    socialHelp: "Academic Writing.",
    contact: "j.kamara@ubuntuafrika.com/ Telno +23276907305",
    family: "Engaged with four children, Sister, Mother and Father.",
    age: "41",
    grade: "Superado satisfactoriamente.",
  },
  {
    name: "Khadija Jalloh",
    cohort: "2021 - 2022",
    photo: "/images/kay.png",
    residence: "Freetown (Sierra Leone)",
    birthPlace: "Freetown",
    familyPlace: "Freetown",
    job: "Masters Students",
    organization: "Nankai University, China",
    socialHelp: "Doing Business",
    contact: "Telno +8617112202889",
    family: "Not married with no child, Brothers, sisters, and mother",
    age: "29",
    grade: "Superado satisfactoriamente.",
  },
  {
    name: "Momoh Sesay",
    cohort: "2021 - 2022",
    photo: "/images/MG_2279-copy.jpg",
    residence: "3 New York Drive Makeni (Sierra Leone)",
    birthPlace: "Masingbeh (Northern Province)",
    familyPlace: "Makeni",
    job: "Junior Software Developer Ubuntu Tech Project in IT area.",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp:
      "Support Social Cooperation Projects for Ubuntu Africa in Sierra Leona and own a small computer shop.",
    contact: "momoh.sesay@ubuntuafrika.com / Telno +23279479939",
    family: "Not married with a child, Brothers, Sisters, Mother and Father",
    age: "34",
    grade: "Superado satisfactoriamente",
  },
  {
    name: "Edward David Thoronka",
    cohort: "2021 - 2022",
    photo: "/images/edward.png",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Makeni",
    familyPlace: "Makeni",
    job: "ICT Coordinator",
    organization: "SWISS Sierra Leone Development Foundation",
    socialHelp: "Teaching and Training.",
    contact: "edwardthoronka077@gmail.com/ Telno +23279404151",
    family: "Married with one child, Brothers, sisters, mother and father.",
    age: "28",
    grade: "Superado satisfactoriamente.",
  },
  {
    name: "David Sapunka Fornah",
    cohort: "2021 - 2022",
    photo: "/images/3-1.jpg",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Binkolo",
    familyPlace: "Makeni",
    job: "Lecturer IT Area.",
    organization: "Central University Sierra Leone",
    socialHelp: "Teaching.",
    contact: "davidsapunkafornah@gmail.com/ Telno +861370204020",
    family: "Not married with two children, Brothers and Mother.",
    age: "34",
    grade: "Superado satisfactoriamente.",
  },
  {
    name: "Yusifu M. Barrie",
    cohort: "2022 - 2023",
    photo: "/images/MG_2285.jpg",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Magburaka",
    familyPlace: "Conakry, Guinea",
    job: "Junior Software Developer Ubuntu Tech Project in IT area.",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp: "Entrepreneur & Web and Mobile Application Developer.",
    contact: "y.barrie@ubuntuafrika.com / Telno +23279506010",
    family: "Not married without children, Brothers, Sisters, Mother",
    age: "29",
    grade: "Superado satisfactoriamente",
  },
  {
    name: "Micheal Humbo",
    cohort: "2022 - 2023",
    photo: "/images/MG_2284.jpg",
    residence: "Block 59 Teko Barracks phase 1 Makeni",
    birthPlace: "Kenema Sierra Leone",
    familyPlace: "Makeni, Sierra Leone",
    job: "Junior Software Developer Ubuntu Tech Project in IT area.",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp: "Web Developer at Link Corporation SL Ltd.",
    contact: "m.humbo@ubuntuafrika.com/ Telno +23277664016",
    family: "Not married with a Child, Brothers, Sister and Father.",
    age: "25",
    grade: "Superado Excelencia.",
  },
  {
    name: "Isatu Magdalene Kamara",
    cohort: "2022 - 2023",
    photo: "/images/MG_2266.jpg",
    residence: "8 SANDA LANE, MAKENI (Sierra Leone)",
    birthPlace: "Makeni",
    familyPlace: "Kenema",
    job: "Junior Software Developer Ubuntu Tech Project in IT area",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp: "ENTERPRENEUR.",
    contact: "m.kamara@ubuntuafrika.com / Telno +23278843894",
    family: "Not married without children, No Brothers, No Sisters, Mother and Father.",
    age: "22",
    grade: "Superado Excelencia.",
  },
  {
    name: "Philip Adikali Sesay",
    cohort: "2022 - 2023",
    photo: "/images/MG_2289.jpg",
    residence: "3 Madina Drive New York, Makeni (Sierra Leone)",
    birthPlace: "Yele",
    familyPlace: "Philip Lane, Magburaka",
    job: "Junior Software Developer Ubuntu Tech Project in IT area.",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp: "Entrepreneur in Wood furniture.",
    contact: "philip.sesay@ubuntuafrika.com/ Telno +232 76385530",
    family: "Not married without children, Brother, Sisters, Mother and Father.",
    age: "36",
    grade: "Superado Excelencia",
  },
  {
    name: "John Turay",
    cohort: "2022 - 2023",
    photo: "/images/MG_2292.jpg",
    residence: "18 Old Mabanta Road, Makeni (Sierra Leone)",
    birthPlace: "Makeni",
    familyPlace: "Makeni",
    job: "Junior Software Developer Ubuntu Tech Project in IT area",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone)",
    socialHelp: "Support Social Cooperation Projects for Ubuntu Africa in Sierra Leona .",
    contact: "j.turay@ubuntuafrika.com/ Telno +23288516317",
    family: "Not married without children, 4 Brothers, 3 Sisters, Mother and Father.",
    age: "26",
    grade: "Superado satisfactoriamente.",
  },
  {
    name: "Amadu Wurie Bah",
    cohort: "2022 - 2023",
    photo: "/images/amadu.png",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Magburaka",
    familyPlace: "Worreh",
    job: "Masters Students",
    organization: "Nankai University, China",
    socialHelp: "Senior Technology Officer at Link Corporation SL Ltd",
    contact: "Telno +23288682144",
    family: "Not married with no child, Brothers, sisters, and mother",
    age: "27",
    grade: "Superado satisfactoriamente.",
  },
  {
    name: "Abdul Karim Jusu",
    cohort: "2022 - 2023",
    photo: "/images/jusu.png",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Kenema",
    familyPlace: "Kenema",
    job: "Deputy Country Director",
    organization: "Families Without Borders Sierra Leone",
    socialHelp: "Teaching and Training.",
    contact: "karimjusu@gmail.com/ Telno +23279693959",
    family: "Not Married with one child, Brothers, sisters, mother and father.",
    age: "26",
    grade: "Superado satisfactoriamente.",
  },
  {
    name: "Abdul Karim Sesay",
    cohort: "2022 - 2023",
    photo: "/images/stud.png",
    residence: "Kambia (Sierra Leone)",
    birthPlace: "Kambia",
    familyPlace: "Kambia",
    job: "Not-Known.",
    organization: "Not-Known",
    socialHelp: "not-Known.",
    contact: "aksesay1@gmail.com/ Telno +23230363129",
    family: "Not married with no children, Brothers and Mother.",
    age: "26",
    grade: "Do not finish the postgraduate.",
  },
  {
    name: "Ibrahim Kargbo",
    cohort: "2023 - 2024",
    photo: "/images/WhatsApp-Image-2024-08-07-at-6.00.44-PM-5.jpeg",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Magburaka",
    familyPlace: "Conakry, Guinea",
    job: "Junior Software Developer Ubuntu Tech Project in IT area.",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp: "Entrepreneur & Web and Mobile Application Developer.",
    contact: "ibrahimrapascojr@gmail.com / Telno +23279506010",
    family: "Not married without children, Brothers, Sisters, Mother",
    age: "29",
    grade: "Superado satisfactoriamente",
  },
  {
    name: "Yeaniva Bayoh",
    cohort: "2023 - 2024",
    photo: "/images/WhatsApp-Image-2024-08-07-at-6.00.44-PM-8.jpeg",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Freetown",
    familyPlace: "Freetown",
    job: "Student",
    organization: "Ubuntu Afrika foundation (Makeni, Sierra Leone)",
    socialHelp: "None.",
    contact: "bayohyeanivaa@gmail.com/ Telno +23276134756/32089792",
    family: "Not Married with one child, Brothers, Sisters, Mother.",
    age: "28: 31",
    grade: "Superado satisfactoriamente.",
  },
  {
    name: "Sulaiman Sesay",
    cohort: "2023 - 2024",
    photo: "/images/WhatsApp-Image-2024-08-07-at-6.00.44-PM.jpeg",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Freetown",
    familyPlace: "Freetown",
    job: "Student.",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp: "Data Manager Volunteer, community Assist.",
    contact: "sulaimansesay@ubuntuafrika.com / Telno +232 88639565",
    family: "Widower, Brothers, Sisters, Mother and Father.",
    age: "27",
    grade: "Superado Excelencia",
  },
  {
    name: "Abubakarr Kanu",
    cohort: "2023 - 2024",
    photo: "/images/WhatsApp-Image-2024-08-07-at-6.00.44-PM-6.jpeg",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Yele",
    familyPlace: "Philip Lane, Magburaka",
    job: "Junior Software Developer Ubuntu Tech Project in IT area.",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp: "Entrepreneur in Wood furniture.",
    contact: "kanubakarr080@gmail.com/ Telno +232 76385530",
    family: "Not married without children, Brother, Sisters, Mother and Father.",
    age: "36",
    grade: "Superado Excelencia.",
  },
  {
    name: "Omaru Calla Kamara",
    cohort: "2023 - 2024",
    photo: "/images/WhatsApp-Image-2024-08-07-at-6.00.44-PM-1.jpeg",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Makeni",
    familyPlace: "Makeni",
    job: "Junior Software Developer Ubuntu Tech Project in IT area",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone)",
    socialHelp: "Support Social Cooperation Projects for Ubuntu Africa in Sierra Leona .",
    contact: "omarucalla@gmail.com/ Telno +23288516317",
    family: "Not married without children, 4 Brothers, 3 Sisters, Mother and Father.",
    age: "26",
    grade: "Superado satisfactoriamente.",
  },
  {
    name: "Sullaiman Kamanda",
    cohort: "2023 - 2024",
    photo: "/images/WhatsApp-Image-2024-08-07-at-6.00.44-PM-2.jpeg",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Lunsar-Port Loko",
    familyPlace: "Makeni",
    job: "Student.",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp: "Photographer and Editor.",
    contact: "sullaimankamada96@gmail.com / Telno +232 79682104",
    family: "Not married without children, Brother, Sisters, Mother and Father Alive.",
    age: "27",
    grade: "Superado Excelencia.",
  },
  {
    name: "Mariama Mansaray",
    cohort: "2023 - 2024",
    photo: "/images/WhatsApp-Image-2024-08-07-at-6.00.44-PM-7.jpeg",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Makeni",
    familyPlace: "Makeni",
    job: "Student",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp: "Business.",
    contact: "mansaraymariama75@gmail.com/ Telno +232 99326441/074041970",
    family: "Not Married with one child, Brothers, Sisters, Father is Alive",
    age: "26",
    grade: "Superado Excelencia.",
  },
  {
    name: "John Momoh Koroma",
    cohort: "2023 - 2024",
    photo: "/images/WhatsApp-Image-2024-08-07-at-6.00.44-PM-4.jpeg",
    residence: "Makeni(Sierra Leone)",
    birthPlace: "Makeni",
    familyPlace: "Kambia",
    job: "Not-Known.",
    organization: "Not-Known",
    socialHelp: "not-Known.",
    contact: "johnnymomohk@gmail.com/ Telno +23230363129",
    family: "Not married with no children, Brothers and Mother.",
    age: "26",
    grade: "Do not finish the postgraduate.",
  },
  {
    name: "John Momoh Sesay",
    cohort: "2025 - 2026",
    photo: "/images/WhatsApp-Image-2026-02-10-at-10.38.57.jpeg",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Freetown",
    familyPlace: "Freetown",
    job: "Student.",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp: "Video Editor, MS Office package tuitor.",
    contact: "johnmsesay1999@gmail.com / Tel no +232 79525354",
    family: "Not married without children, Brothers, Sisters, Father Alive, Mother Late",
    age: "26",
    grade: "Superado Excelencia.",
  },
  {
    name: "Gifty Hemans",
    cohort: "2025 - 2026",
    photo: "/images/gifty-hemans.jpg",
    residence: "Lunsar (Sierra Leone)",
    birthPlace: "Abaodze, Western Ghana",
    familyPlace: "Freetown",
    job: "Student.",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp: "ICT Assistant",
    contact: "giftyhemans8@gmail.com / Telno +232 30456800/+232 72756253",
    family: "Not married without children, Brother, Mother and Father Alive.",
    age: "25",
    grade: "Superado Excelencia.",
  },
  {
    name: "Abdulai Turay",
    cohort: "2025 - 2026",
    photo: "/images/abdulai-turay-v2.jpg",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "BO city",
    familyPlace: "Makeni",
    job: "Student.",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp: "Graphics Designer and I.T Consultant",
    contact: "turayabdulai570@gmail.com / Telno +232 79163173",
    family: "Not married without children, Brothers, Sister, Mother and Father Alive.",
    age: "26",
    grade: "Superado Excelencia.",
  },
  {
    name: "Philip Jalloh",
    cohort: "2025 - 2026",
    photo: "/images/WhatsApp-Image-2026-02-10-at-12.21.57.jpeg",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Magburaka, Tonkolili District",
    familyPlace: "Magburaka",
    job: "Student.",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp: "ICT Assistance and Teacher.",
    contact: "jallohphilip1999@gmail.com / Telno +232 78628300",
    family: "Not married with one child, Brother, Sisters, Mother.",
    age: "26",
    grade: "Superado Excelencia.",
  },
  {
    name: "Abdul Bangura",
    cohort: "2025 - 2026",
    photo: "/images/WhatsApp-Image-2026-02-10-at-14.15.35.jpeg",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Masingbi",
    familyPlace: "Masingbi, Sierra Leone",
    job: "Student, Ubuntu Postgraduate Software Development Training",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp: "Business",
    contact: "abdulbangura023@gmail.com/Telno +23288180366",
    family: "Not married, without children, father, mother, brothers and sisters",
    age: "29",
    grade: "Superado Excelencia.",
    internalNotes:
      "The live WordPress page repeats this same contact block for Moses Lamin Massaquoi and Saidu T. H. Kamara. Preserved as published; review in Sanity.",
  },
  {
    name: "Moses Lamin Massaquoi",
    cohort: "2025 - 2026",
    photo: "/images/WhatsApp-Image-2026-02-10-at-14.15.35.jpeg",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Masingbi",
    familyPlace: "Masingbi, Sierra Leone",
    job: "Student, Ubuntu Postgraduate Software Development Training",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp: "Business",
    contact: "abdulbangura023@gmail.com/Telno +23288180366",
    family: "Not married, without children, father, mother, brothers and sisters",
    age: "29",
    grade: "Superado Excelencia.",
    internalNotes:
      "WordPress listing duplicates Abdul Bangura contact details. Flagged for editorial correction.",
  },
  {
    name: "Saidu T. H. Kamara",
    cohort: "2025 - 2026",
    photo: "/images/WhatsApp-Image-2026-02-10-at-14.15.35.jpeg",
    residence: "Makeni (Sierra Leone)",
    birthPlace: "Masingbi",
    familyPlace: "Masingbi, Sierra Leone",
    job: "Student, Ubuntu Postgraduate Software Development Training",
    organization: "Ubuntu Afrika Foundation (Makeni, Sierra Leone).",
    socialHelp: "Business",
    contact: "abdulbangura023@gmail.com/Telno +23288180366",
    family: "Not married, without children, father, mother, brothers and sisters",
    age: "29",
    grade: "Superado Excelencia.",
    internalNotes:
      "WordPress listing duplicates Abdul Bangura contact details. Flagged for editorial correction.",
  },
];
